spring:
  application:
    name: eureka-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yueranan/privoder
          username: 2460989573@qq.com
          password: woaijiaqing/1
          basedir: G:\assit_java\save_mq_file
  rabbitmq:
    host: 192.168.0.113
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8093